### ISSUE TITLE
Using JWS "as is" gives a cleaner and more powerful design

### ISSUE THREAD

**Issue by cyberphone** [w3c-dvcg/lds-rsa2017#1]
Currently crypto related definitions are divided between the Linked Data Signature definitions and JWS.

I suggest that JWS detached unenecode signatures are used exactly as specified by the RFC which means that "creator" would be replaced by JWS's "jku" while "RsaSignature2017" would leave everything RSA to the JWS object to cater for.  In the LDS container you would then rather specify something like "RdfSignature2017".

This should make LDS fully compatible with JWS as well as inheriting all the other other goodies including EC signatures as well as HMAC and PKI support.  Being able using JWK for in-lined public keys rather than URL-based keys is also quite useful since all keys do not necessarily live on public URLs.

In such a setting I would consider renaming "signatureValue" to something like "signature", "jws", or "jwsSignature" and using the JWS compact notation as the actual value.

The current specification doesn't mention that the signature element must be excluded from the canonicalization process.

**Comment by msporny** [comment]
@cyberphone could you provide an example of what such a signature would look like?

**Comment by msporny** [comment]
> The current specification doesn't mention that the signature element must be excluded from the canonicalization process

This is in step #3 of the Signature Verification Algorithm: https://w3c-dvcg.github.io/ld-signatures/#signature-verification-algorithm

**Comment by msporny** [comment]
> Being able using JWK for in-lined public keys rather than URL-based keys is also quite useful since all keys do not necessarily live on public URLs.

Linked Data signatures don't require URLs for public keys. You can use any valid URI. You can also specify the public key by using a JSON object in the "creator" field (and list other properties of the key, such as alternative encodings), which you can't do with "jku". 

For example, this is possible w/ the Linked Data Signatures format (and is impossible to do with JWKs):

``` json
{
  "@context": "https://w3id.org/identity/v1",
  "title": "Hello World!",
  "signature": {
    "type": "RsaSignature2017",
    // you can't do the following in JWK
    "creator": { 
      "id": "https://example.com/i/pat/keys/5",
      "type": "HardwareRsaKey",
      "description": "This is Pat's signing key stored on her mobile phone",
      "keyAuthentication": "TwoFactorOneTimePassword",
      "publicKeyPem": "-----BEGIN PUBLIC KEY-----..."
    },
    "created": "2017-09-23T20:21:34Z",
    "domain": "example.org",
    "nonce": "2bbgh3dgjg2302d-d2b3gi423d42",
    "signatureValue": "eyJ0eXAiOiJK...gFWFOEjXk"
  }
}
```

**Comment by cyberphone** [comment]
@msporny 

> Linked Data signatures don't require URLs for public keys. You can use any valid URI. You can also specify the public key by using a JSON object in the "creator" field (and list other properties of the key, such as alternative encodings), which you can't do with "jku".

What I'm suggesting is simply that "Everything Crypto" should go to the JWS container, where a JWK element would be used for specifying public keys: https://tools.ietf.org/html/rfc7515#section-4.1.3

```json
{
  "@context": ["http://schema.org/", "https://w3id.org/security/v1"],
  "description": "Hello world!",
  "signature": {
    "type": "RdfSignature2017",
    "created": "2017-10-24T05:33:31Z",
    "domain": "example.com",
    "jws": "eyiOiJJ0eXAK...EjXkgFWFO"
  }
}
```
Protected header:
{"alg":"RS256","b64":false,"crit":["b64"], "jku":"https://example.com/jdoe/keys/1"}

**Comment by cyberphone** [comment]
Using in lined RSA public keys:
{"alg":"RS256","b64":false,"crit":["b64"], "jwk":{"kty":"RSA","n":"ghgh6d54s4e44s4etcetetc", "e":"AQAB"}}

**Comment by cyberphone** [comment]
It is strictly put only the "signatureValue" property (which I called "jws" above) that needs to be removed from canonicalization.

**Comment by msporny** [comment]
> {"alg":"RS256","b64":false,"crit":["b64"], "jwk":{"kty":"RSA","n":"ghgh6d54s4e44s4etcetetc", "e":"AQAB"}}

This unnecessarily bloats the signature value and is not as flexible as the key formats used in Linked Data Signatures. 

-1 to moving the key information into the JWS as it bloats the signature and does not provide the level of flexibility that we need for our use cases.

**Comment by OR13** [comment]
agreed. closing.
