### ISSUE TITLE
Modifications to Signature Algorithm unclear

### ISSUE THREAD

**Issue by mburrows02** [w3c-dvcg/lds-rsa2017#4]
I might be misunderstanding RFC 7797, but the following statement in section 3.1.1 seems contradictory:

>  Take tbs, which is the data to be signed, as input and generate a JOSE Web Signature structure where the headers are: {"alg":"RS256","b64":false,"crit":["b64"]} and the payload is a URL-safe Base64 encoding of tbs.

What's the purpose of setting b64 to false but still Base64-encoding the payload? Or is there an error there?

**Comment by dlongley** [comment]
@mburrows02,

I think it's an error. Here's the reference implementation:

https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/suites/JwsLinkedDataSignature.js#L64-L93

**Comment by OR13** [comment]
Closing.
